API_KEY = "YOUR_BITGET_API_KEY"
API_SECRET = "YOUR_BITGET_SECRET"
PASSPHRASE = "YOUR_PASSPHRASE"

BASE_URL = "https://api.bitget.com"

SYMBOLS = ["BTCUSDT", "ETHUSDT", "SOLUSDT"]

TIMEFRAME = "5m"

RISK_PER_TRADE = 0.01
MAX_TRADES = 2

TP1 = 0.006   # 0.6%
TP2 = 0.012   # 1.2%
SL = 0.005    # 0.5%

LEVERAGE = 4
